### PR TITLE
fix: status module trailing space transparancy

### LINKED ISSUE #242: Issue with transparency when setting @catppuccin_status_background "default"
### Is there an existing issue outlining your improvement?

- [X] I have searched the existing issues and my improvement has not been raised yet.

### What would you like to see added and/or changed?

change `module_builder.sh` line 10
`local show_text="#[fg=$thm_fg,bg=$thm_gray] $text"`
to 
`local show_text="#[fg=$thm_fg,bg=default] $text"`

this will allow to set the bg color of the space character between the icon and the text to the default bg color of the terminal

### PR DESCRIPTION
**Pull request by vdbe**
Thank you @64rl0 for noticing it and suggesting a fix.

Closes #242

### CODE REVIEW

File: builder/module_builder.sh [hunk 1]
```diff
@@ -7,18 +7,18 @@ build_status_module() {
...
-      local show_right_separator="#[fg=$thm_gray,bg=$thm_gray,nobold,nounderscore,noitalics]$status_right_separator"
-
+      bg="$thm_gray"
     else
-      local show_left_separator="#[fg=$color,bg=default,nobold,nounderscore,noitalics]$status_left_separator"
-      local show_right_separator="#[fg=$thm_gray,bg=default,nobold,nounderscore,noitalics]$status_right_separator"
+      bg="default"
     fi
 
+    local show_text="#[fg=$thm_fg,bg=$bg] $text"
```
Comment (vdbe) [inline builder/module_builder.sh:19]: This doesn't need to be changed and background needs to be thm_gray
